import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <main class="min-h-screen bg-[#0b0b0d] text-foreground">
      <header class="border-b border-white/10 bg-card/80 px-5 py-4 backdrop-blur lg:px-10"><div class="mx-auto flex max-w-[1500px] items-center justify-between"><a routerLink="/" class="text-lg font-bold">shof<span class="text-primary">tv</span> <span class="ml-2 text-xs font-normal uppercase tracking-wider text-muted-foreground">Studio</span></a><div class="flex items-center gap-4"><a routerLink="/browse" class="text-xs text-muted-foreground hover:text-foreground">View platform</a><span class="grid h-9 w-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">SA</span></div></div></header>
      <div class="mx-auto grid max-w-[1500px] gap-8 px-5 py-8 lg:grid-cols-[220px_1fr] lg:px-10">
        <aside class="hidden lg:block"><p class="eyebrow">Workspace</p><nav class="mt-5 space-y-1"><a *ngFor="let item of nav" [ngClass]="{ 'bg-primary/10': item.active, 'text-primary': item.active }" class="flex items-center justify-between rounded-xl px-4 py-3 text-sm font-semibold text-secondary-foreground">{{ item.label }}<span *ngIf="item.count" class="rounded-full bg-white/10 px-2 py-0.5 text-[10px]">{{ item.count }}</span></a></nav><div class="mt-12 rounded-2xl border border-primary/20 bg-primary/5 p-4"><p class="text-xs font-bold text-primary">Release checklist</p><p class="mt-2 text-xs leading-relaxed text-muted-foreground">Review content, confirm metadata, and publish when ready.</p></div></aside>
        <section><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Monday, September 7</p><h1 class="mt-2 text-4xl font-extrabold tracking-tight">Good morning, Studio.</h1></div><button type="button" class="rounded-full bg-primary px-5 py-3 text-xs font-bold uppercase tracking-wider text-primary-foreground">+ Add title</button></div>
          <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article *ngFor="let metric of metrics" class="rounded-2xl border border-white/10 bg-card p-5"><p class="text-xs text-muted-foreground">{{ metric.label }}</p><p class="mt-3 text-3xl font-extrabold">{{ metric.value }}</p><p class="mt-2 text-xs text-success">{{ metric.change }} vs last month</p></article></div>
          <div class="mt-6 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><section class="rounded-2xl border border-white/10 bg-card p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Catalog health</p><h2 class="mt-2 text-xl font-bold">Publishing queue</h2></div><button class="text-xs font-bold uppercase tracking-wider text-primary">View all →</button></div><div class="mt-6 space-y-4"><div *ngFor="let title of queue" class="flex items-center gap-4 border-b border-white/10 pb-4 last:border-0 last:pb-0"><img [src]="title.image" [alt]="title.name" class="h-12 w-9 rounded object-cover" /><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{ title.name }}</p><p class="mt-1 text-xs text-muted-foreground">{{ title.type }} · Updated {{ title.updated }}</p></div><span [class.text-success]="title.status === 'Published'" [class.text-primary]="title.status === 'Review'" class="text-xs font-bold">{{ title.status }}</span></div></div></section><section class="rounded-2xl border border-white/10 bg-card p-6"><p class="eyebrow">Viewer activity</p><h2 class="mt-2 text-xl font-bold">This week</h2><div class="mt-8 flex h-40 items-end gap-2"><div *ngFor="let day of activity" class="flex flex-1 flex-col items-center gap-2"><div class="w-full rounded-t-md bg-primary/70" [style.height.%]="day.value"></div><span class="text-[10px] text-muted-foreground">{{ day.label }}</span></div></div><div class="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-sm"><span class="text-muted-foreground">Average watch time</span><strong>47m 22s</strong></div></section></div>
          <section class="mt-6 rounded-2xl border border-white/10 bg-card p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Moderation</p><h2 class="mt-2 text-xl font-bold">Reports needing attention</h2></div><span class="rounded-full bg-accent/15 px-3 py-1 text-xs font-bold text-accent">3 open</span></div><div class="mt-5 grid gap-3 md:grid-cols-3"><div *ngFor="let report of reports" class="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div class="flex justify-between gap-3"><p class="text-sm font-semibold">{{ report.title }}</p><span class="text-[10px] text-muted-foreground">{{ report.time }}</span></div><p class="mt-2 text-xs leading-relaxed text-muted-foreground">{{ report.reason }}</p><button class="mt-4 text-xs font-bold uppercase tracking-wider text-primary">Review report →</button></div></div></section>
        </section>
      </div>
    </main>
  `,
})
export class AdminComponent {
  readonly nav = [{ label: 'Overview', active: true }, { label: 'Content library', count: 128 }, { label: 'Publishing queue', count: 4 }, { label: 'Viewers', count: 12400 }, { label: 'Reports', count: 3 }, { label: 'Analytics' }];
  readonly metrics = [{ label: 'Monthly viewers', value: '124.8K', change: '+18.4%' }, { label: 'Hours watched', value: '86.2K', change: '+12.7%' }, { label: 'Premium conversion', value: '8.6%', change: '+2.1%' }, { label: 'Open reports', value: '3', change: '-25.0%' }];
  readonly queue = [
    { name: 'After the Last Light', type: 'Series · 8 episodes', updated: '2h ago', status: 'Published', image: '/assets/img/shoftv-poster-desert.jpg' },
    { name: 'The Long Round', type: 'Documentary · 1h 47m', updated: '5h ago', status: 'Review', image: '/assets/img/shoftv-poster-fight.jpg' },
    { name: 'Little Lanterns', type: 'Kids · 12 episodes', updated: 'Yesterday', status: 'Published', image: '/assets/img/shoftv-poster-summer.jpg' },
  ];
  readonly activity = [{ label: 'Mon', value: 64 }, { label: 'Tue', value: 78 }, { label: 'Wed', value: 52 }, { label: 'Thu', value: 87 }, { label: 'Fri', value: 70 }, { label: 'Sat', value: 96 }, { label: 'Sun', value: 82 }];
  readonly reports = [{ title: 'The Long Round', time: '34m', reason: 'Viewer reported inaccurate content rating.' }, { title: 'Neon Hours', time: '2h', reason: 'A copyright claim needs a content review.' }, { title: 'Blue Note', time: '1d', reason: 'Subtitle timing was flagged by 2 viewers.' }];
}