import { PlatformTitle } from './platform.models';

export const PLATFORM_TITLES: readonly PlatformTitle[] = [
  {
    id: 'after-the-last-light',
    title: 'After the Last Light',
    tagline: 'Some stories only begin after dark.',
    description: 'A quiet, emotionally charged series about the people who keep a coastal city moving long after the tourists leave.',
    kind: 'Series',
    category: 'Drama',
    year: 2026,
    maturity: '12',
    runtime: '8 episodes',
    rating: 8.8,
    image: '/home/posters/desert.jpg',
    backdrop: '/home/hero.jpg',
    badge: 'New',
    episodes: 8,
    featured: true,
    isPremium: true,
    cast: ['Nour El-Sherif', 'Mina Hany', 'Laila Tarek'],
  },
  {
    id: 'blue-note',
    title: 'Blue Note',
    tagline: 'Every great escape has a soundtrack.',
    description: 'A touring pianist returns home to rebuild a lost club, one unforgettable night at a time.',
    kind: 'Movie',
    category: 'Drama',
    year: 2025,
    maturity: '12',
    runtime: '2h 04m',
    rating: 8.5,
    image: '/home/posters/jazz.jpg',
    backdrop: '/home/posters/jazz.jpg',
    badge: '4K',
    isPremium: true,
    cast: ['Omar Youssef', 'Sara Adel'],
  },
  {
    id: 'neon-hours',
    title: 'Neon Hours',
    tagline: 'The city never tells the whole story.',
    description: 'Three strangers cross paths over one restless night in a city built on secrets.',
    kind: 'Movie',
    category: 'Comedy',
    year: 2025,
    maturity: '16',
    runtime: '1h 51m',
    rating: 8.1,
    image: '/home/posters/rain.jpg',
    backdrop: '/home/posters/rain.jpg',
    badge: 'Top 10',
    cast: ['Yara Sameh', 'Karim Fawzi'],
  },
  {
    id: 'august-again',
    title: 'August, Again',
    tagline: 'You can go home. You just can’t go back.',
    description: 'A warm ensemble series about family, second chances, and one summer that refuses to end.',
    kind: 'Series',
    category: 'Comedy',
    year: 2026,
    maturity: '7',
    runtime: '6 episodes',
    rating: 8.3,
    image: '/home/posters/summer.jpg',
    backdrop: '/home/posters/summer.jpg',
    badge: 'New',
    episodes: 6,
    isPremium: true,
    cast: ['Malak Hassan', 'Adam Fadel'],
  },
  {
    id: 'the-long-round',
    title: 'The Long Round',
    tagline: 'Champions are made between the bells.',
    description: 'An intimate ringside documentary following three fighters through the biggest season of their lives.',
    kind: 'Movie',
    category: 'Sports',
    year: 2025,
    maturity: '12',
    runtime: '1h 47m',
    rating: 9.1,
    image: '/home/posters/fight.jpg',
    backdrop: '/home/posters/fight.jpg',
    badge: 'Original',
    isPremium: true,
    cast: ['Hassan Ali', 'Mariam Fathy'],
  },
  {
    id: 'desert-lines',
    title: 'Desert Lines',
    tagline: 'The road remembers everyone.',
    description: 'A visual journey through the communities and artists shaping a new desert culture.',
    kind: 'Movie',
    category: 'Documentary',
    year: 2024,
    maturity: 'U',
    runtime: '2h 12m',
    rating: 8.7,
    image: '/home/posters/desert.jpg',
    backdrop: '/home/posters/desert.jpg',
    badge: 'HD',
    cast: ['Hala Mostafa'],
  },
  {
    id: 'match-night-live',
    title: 'Match Night Live',
    tagline: 'The whole stadium, in your living room.',
    description: 'Live coverage, expert analysis, and the moments everyone will be talking about.',
    kind: 'Live',
    category: 'Live',
    year: 2026,
    maturity: 'U',
    runtime: 'Live now',
    rating: 9.4,
    image: '/home/cinema.jpg',
    backdrop: '/home/cinema.jpg',
    badge: 'Live',
    isPremium: true,
    cast: ['ShofTV Sports Desk'],
  },
  {
    id: 'little-lanterns',
    title: 'Little Lanterns',
    tagline: 'Big adventures start small.',
    description: 'A bright animated adventure for curious families who believe every corner hides a story.',
    kind: 'Series',
    category: 'Kids',
    year: 2025,
    maturity: 'U',
    runtime: '12 episodes',
    rating: 8.6,
    image: '/home/posters/summer.jpg',
    backdrop: '/home/posters/summer.jpg',
    badge: 'Family',
    episodes: 12,
    cast: ['The Lantern Crew'],
  },
];

export const CATEGORIES: readonly Exclude<import('./platform.models').ContentCategory, 'All'>[] = [
  'Drama',
  'Documentary',
  'Comedy',
  'Sports',
  'Kids',
  'Live',
];